defaults:
  - _self_
  - /cluster: local
  - /algorithm: dqn
  - /environment: cc_cartpole
  - search_space: dqn
  - /experiments: cc_cartpole_dqn
  - override hydra/sweeper: HyperRS

hydra:
  sweeper:
    n_trials: 256
    search_space: ${search_space}
    sweeper_kwargs:
      max_parallelization: 0.1 #  hence, only 25 jobs per batch
      job_array_size_limit: 100
  run:
    dir: results/sobol/${algorithm}_${autorl.env_name}/${autorl.seed}
  sweep:
    dir: results/sobol/${algorithm}_${autorl.env_name}/${autorl.seed}
  job:
    chdir: true

load_checkpoint: ""
jax_enable_x64: false
search_space.seed: 0

autorl:
  seed: 42
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  deterministic_eval: ${environment.deterministic_eval}
  nas_config: ${nas_config}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  state_features: []
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  n_steps: 10
  n_eval_steps: 10
  n_eval_episodes: 128
