defaults:
  - _self_
  - /cluster: local
  - /algorithm: dqn
  - /environment: cc_cartpole
  - /search_space: dqn
  - /experiments: cc_cartpole_dqn_smac
  - override hydra/sweeper: HyperSMAC

hydra:
  sweeper:
    n_trials: 300
    search_space: ${search_space}
    sweeper_kwargs:
      max_budget: ${environment.n_total_timesteps}
      warmstart_file: runscripts/configs/initial_design/${experiment_name}.csv
      optimizer_kwargs:
        smac_facade:
          _target_: smac.facade.blackbox_facade.BlackBoxFacade
          _partial_: true
          overwrite: true
        scenario:
          seed: ${smac_seed}
          n_trials: ${hydra.sweeper.n_trials}
          deterministic: false
          n_workers: 1
          name: ${experiment_name}
          output_directory: results/smac/${algorithm}_${autorl.env_name}/${smac_seed}/smac_output
        intensifier:
          _target_: smac.intensifier.Intensifier
          _partial_: true
          max_config_calls: 10   # the number of seeds
          seed: ${smac_seed}
        initial_design:
          _target_: smac.initial_design.sobol_design.SobolInitialDesign
          _partial_: true
          n_configs: 0
          # additional_configs: ${read_additional_configs:runscripts/configs/initial_design/${experiment_name}.csv,${search_space}}
      # seeds: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
      maximize: true
      deterministic: false
  run:
    dir: results/smac/${algorithm}_${autorl.env_name}/${smac_seed}/${seed}
  sweep:
    dir: results/smac/${algorithm}_${autorl.env_name}/${smac_seed}/${seed}
  job:
    chdir: true

experiment_name: ""
load_checkpoint: ""
smac_seed: 0
jax_enable_x64: false
seed: 42

autorl:
  seed: ${seed}
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  nas_config: ${nas_config}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  state_features: []
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  n_steps: 10
  n_eval_steps: 10
  n_eval_episodes: 128
