defaults:
  - _self_
  - /cluster: local
  - /algorithm: dqn
  - /environment: cc_cartpole
  - /search_space: dqn
  - /experiments: cc_cartpole_dqn
  - override hydra/sweeper: HyperSMAC

hydra:
  sweeper:
    n_trials: 254
    budget: ${multiply:${environment.n_total_timesteps},32}
    budget_variable: autorl.n_total_timesteps
    search_space: ${search_space}
    sweeper_kwargs:
      seeds: [0, 1, 2]
      maximize: true
      max_job_array
      min_budget: ${divide:${environment.n_total_timesteps},100}
      max_budget: ${environment.n_total_timesteps} 
      job_array_size_limit: 1
      optimizer_kwargs:
        smac_facade:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade
          _partial_: true
          overwrite: true
        intensifier:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade.get_intensifier
          _partial_: true
          eta: 4
        scenario:
          seed: ${smac_seed}
          n_trials: ${hydra.sweeper.n_trials}
          min_budget: ${hydra.sweeper.sweeper_kwargs.min_budget}
          max_budget: ${environment.n_total_timesteps}
          deterministic: true
          n_workers: 1
  run:
    dir: results/smac_mf/${algorithm}_${autorl.env_name}/${smac_seed}/${seed}
  sweep:
    dir: results/smac_mf/${algorithm}_${autorl.env_name}/${smac_seed}/${seed}
  job:
    chdir: true

load_checkpoint: ""
smac_seed: 0
jax_enable_x64: false
seed: 42

autorl:
  seed: ${seed}
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  nas_config: ${nas_config}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  state_features: []
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  n_steps: 10
  n_eval_steps: 1
  n_eval_episodes: 128
