seed: 0
hyperparameters:
  hp_config.alpha:
    type: uniform_float
    upper: 1.0
    lower: 0.0
    default: 1.0
    log: false
  hp_config.alpha_auto:
    type: categorical
    choices:
      - true
      - false
    default: true
  hp_config.buffer_alpha:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 0.9
    log: false
  hp_config.buffer_batch_size:
    type: categorical
    choices:
      - 64
      - 128
      - 256
      - 512
    default: 256
  hp_config.buffer_beta:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 0.9
    log: false
  hp_config.buffer_epsilon:
    type: uniform_float
    upper: 1e-4
    lower: 1e-9
    default: 1e-7
    log: true
  hp_config.buffer_prio_sampling:
    type: categorical
    choices:
      - true
      - false
    default: false
  hp_config.buffer_size:
    type: uniform_int
    upper: 1000000
    lower: 1
    default: 1000000
    log: false
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    default: 0.0003
    log: true
  hp_config.learning_starts:
    type: uniform_int
    upper: 1024
    lower: 0
    default: 128
    log: false
  hp_config.target_update_interval:
    type: uniform_int
    upper: 1000
    lower: 1
    default: 1000
    log: false
  hp_config.use_target_network:
    type: categorical
    choices:
      - true
      - false
    default: true
  hp_config.tau:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 1.0
    log: false
conditions:
  - child: hp_config.tau
    parent: hp_config.use_target_network
    value: true
    type: EQ
  - child: hp_config.target_update_interval
    parent: hp_config.use_target_network
    value: true
    type: EQ
  - child: hp_config.buffer_epsilon
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
  - child: hp_config.buffer_alpha
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
  - child: hp_config.buffer_beta
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
