seed: 0
hyperparameters:
  hp_config.buffer_prio_sampling:
    type: categorical
    choices:
      - true
      - false
    default: false
  hp_config.buffer_alpha:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 0.9
    log: false
  hp_config.buffer_beta:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    default: 0.9
    log: false
  hp_config.buffer_epsilon:
    type: uniform_float
    upper: 1e-4
    lower: 1e-9
    default: 1e-7
    log: true
  hp_config.buffer_batch_size:
    type: categorical
    choices:
      - 512
      - 1024
      - 2048
    default: 1024
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    default: 0.0003
    log: true
  hp_config.learning_starts:
    type: uniform_int
    upper: 16384
    lower: 0
    default: 8192
    log: false
  hp_config.tau:
    type: uniform_float
    upper: 1.0
    lower: 0.01
    log: false
  hp_config.reward_scale:
    type: uniform_float
    upper: 10.0
    lower: 0.1
    log: true
conditions:
  - child: hp_config.buffer_epsilon
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
  - child: hp_config.buffer_alpha
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
  - child: hp_config.buffer_beta
    parent: hp_config.buffer_prio_sampling
    value: true
    type: EQ
