# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    gres: "gpu:1"
    timeout_min: 2880
    partition: c23g
    cpus_per_task: 16
    mem_per_cpu: 2000M
    account: p0021208
    setup:
      - export JAX_PLATFORM_NAME=gpu
      - source /rwthfs/rz/cluster/home/oh751555/i14/arlbench/.venv/bin/activate
      - module load CUDA/12.4.0
