# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: Kathleen
    timeout_min: 2880
    cpus_per_task: 16
    mem_per_cpu: 1000M
    setup:
      - export JAX_PLATFORM_NAME=cpu
      - source /home/dierkes/projects/arlbench/.venv
