# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: gpu
    gres: "gpu:a100:1"
    cpus_per_task: 16
    mem_gb: 16
    timeout_min: 240
    setup:
      - export JAX_PLATFORM_NAME=gpu
