defaults:
  - _self_
  - /algorithm: dqn
  - /environment: cc_cartpole
  - /search_space: dqn
  - override hydra/sweeper: HyperSMAC

hydra:
  sweeper:
    n_trials: 16
    budget_variable: autorl.n_total_timesteps
    search_space: ${search_space}
    sweeper_kwargs:
      maximize: true
      min_budget: 10000
      max_budget: ${environment.n_total_timesteps} 
      optimizer_kwargs:
        smac_facade:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade
          _partial_: true
        intensifier:
          _target_: smac.facade.multi_fidelity_facade.MultiFidelityFacade.get_intensifier
          _partial_: true
          eta: 2
          n_seeds: 1
        scenario:
          seed: ${smac_seed}
          n_trials: ${hydra.sweeper.n_trials}
          min_budget: ${hydra.sweeper.sweeper_kwargs.min_budget}
          max_budget: ${environment.n_total_timesteps}
          deterministic: false
          n_workers: 1
          output_directory: ${hydra.sweep.dir}
      seeds: [42, 43, 44]
  run:
    dir: results/smac/${algorithm}_${autorl.env_name}/${smac_seed}/${seed}
  sweep:
    dir: results/smac/${algorithm}_${autorl.env_name}/${smac_seed}/${seed}
  job:
    chdir: true

load_checkpoint: ""
smac_seed: 0
jax_enable_x64: ${environment.jax_enable_x64}
seed: 42

autorl:
  seed: ${seed}
  env_framework: ${environment.framework}
  env_name: ${environment.name}
  env_kwargs: ${environment.kwargs}
  eval_env_kwargs: ${environment.eval_kwargs}
  n_envs: ${environment.n_envs}
  algorithm: ${algorithm}
  cnn_policy: ${environment.cnn_policy}
  nas_config: ${nas_config}
  n_total_timesteps: ${environment.n_total_timesteps}
  checkpoint: []
  checkpoint_name: "default_checkpoint"
  checkpoint_dir: "/tmp"
  state_features: []
  objectives: ["reward_mean"]
  optimize_objectives: "upper"
  n_eval_steps: 10
  n_eval_episodes: 128
