# @package _global_
defaults:
  - override /environment: box2d_lunar_lander_continuous
  - override /algorithm: ppo

environment:
  n_envs: 16
  n_total_timesteps: 1000000

hp_config:
  minibatch_size: 64
  learning_rate: 0.0003
  n_steps: 1024
  update_epochs: 4
  gamma: 0.999
  gae_lambda: 0.98
  clip_eps: 0.2
  ent_coef: 0.01
  max_grad_norm: 0.5
  normalize_observations: False

nas_config:
  activation: tanh
  hidden_size: 64
