# @package _global_
defaults:
  - override /environment: box2d_lunar_lander_continuous
  - override /algorithm: sac   

environment:
  n_envs: 4
  n_total_timesteps: 500000

hp_config:
  buffer_batch_size: 256
  buffer_size: 1000000
  tau: 0.01
  gradient_steps: 4
  gamma: 0.99
  learning_rate: 0.00073
  learning_starts: 10000
  target_update_interval: 1
  train_freq: 1
  normalize_observations: False

nas_config:
  activation: relu
  hidden_size: 400
