# @package _global_
defaults:
  - override /environment: box2d_lunar_lander    
  - override /algorithm: ppo    

# https://huggingface.co/sb3/ppo-PongNoFrameskip-v4
environment:
  n_envs: 16
  n_total_timesteps: 1000000

hp_config:
  minibatch_size: 64
  clip_eps: 0.2
  ent_coef: 0.01
  gamma: 0.999
  gae_lambda: 0.98
  learning_rate: 0.0003
  update_epochs: 4
  n_steps: 1024
  vf_coef: 0.5
  normalize_observations: False

nas_config:
  activation: relu
  hidden_size: 256
