# @package _global_
defaults:
  - override /environment: brax_hopper
  - override /algorithm: sac

environment:
  n_envs: 64
  n_total_timesteps: 5000000

hp_config:
  buffer_batch_size: 1024
  buffer_size: 1000000
  gradient_steps: 8
  learning_rate: 0.0003
  learning_starts: 8192
  target_update_interval: 1
  train_freq: 1
  reward_scale: 1.0
  tau: 0.005
  normalize_observations: True

nas_config:
  activation: relu
  hidden_size: 256
