# @package _global_
defaults:
  - override /environment: cc_cartpole    
  - override /algorithm: ppo       

# https://huggingface.co/sb3/ppo-CartPole-v1
environment:
  n_envs: 8
  n_total_timesteps: 100000

hp_config:
  minibatch_size: 256
  # since we do not support clip_eps schedules we set clip_eps to a fixed value
  clip_eps: 0.2
  ent_coef: 0.0
  gae_lambda: 0.8
  gamma: 0.98
  # since we do not support learning rate schedules we set learning_rate to a fixed value
  learning_rate: 0.001
  update_epochs: 20
  n_steps: 32
  normalize_observations: False
