# @package _global_
defaults:
  - override /environment: cc_pendulum    
  - override /algorithm: ppo       

# https://huggingface.co/sb3/ppo-Pendulum-v1
environment:
  n_envs: 4
  n_total_timesteps: 100000

hp_config:
  minibatch_size: 256
  # since we do not support clip_eps schedules we set clip_eps to a fixed value
  clip_eps: 0.2
  ent_coef: 0.0
  gae_lambda: 0.95
  gamma: 0.9
  # since we do not support learning rate schedules we set learning_rate to a fixed value
  learning_rate: 0.001
  update_epochs: 10
  n_steps: 1024
  normalize_observations: False

nas_config:
  activation: tanh
  hidden_size: 64
