# @package _global_
defaults:
  - override /environment: minigrid_door_key
  - override /algorithm: ppo    

# https://huggingface.co/sb3/ppo-PongNoFrameskip-v4
environment:
  n_envs: 8
  n_total_timesteps: 1000000

hp_config:
  minibatch_size: 64
  clip_eps: 0.2
  ent_coef: 0.0
  gamma: 0.99
  gae_lambda: 0.98
  learning_rate: 0.00025
  update_epochs: 10
  n_steps: 32
  vf_coef: 0.5
  normalize_observations: True

