# @package _global_
defaults:
  - override /environment: minigrid_door_key
  - override /algorithm: dqn    

environment:
  n_envs: 4
  n_total_timesteps: 1000000

hp_config:
  buffer_batch_size: 32
  buffer_size: 1000000
  target_epsilon: 0.05
  gradient_steps: 1
  gamma: 0.99
  learning_rate: 0.0001
  learning_starts: 100
  target_update_interval: 10000
  train_freq: 1
  normalize_observations: True

