# @package _global_
defaults:
  - override /environment: mujoco_ant    
  - override /algorithm: sac    

# https://huggingface.co/sb3/sac-Ant-v3
environment:
  n_envs: 1

hp_config:
  normalize_observations: True
  n_total_timesteps: 1000000
  learning_starts: 10000
  learning_rate: 0.0003
  minibatch_size: 256
  tau: 0.005
  gamma: 0.99
  train_freq: 1
  gradient_steps: 1
  target_update_interval: 1

nas_config:
  activation: relu
  hidden_size: 256

jax_enable_x64: True
