# @package _global_
defaults:
  - override /environment: mujoco_ant    
  - override /algorithm: ppo       

# https://huggingface.co/sb3/ppo-Ant-v3
environment:
  n_envs: 1

hp_config:
  normalize_observations: True
  n_total_timesteps: 1000000
  n_steps: 2048
  learning_rate: 0.0003
  minibatch_size: 64
  update_epochs: 10
  ent_coef: 0.0
  gamma: 0.99
  gae_lambda: 0.95

nas_config:
    activation: tanh
    hidden_size: 256

jax_enable_x64: True
