# @package _global_
defaults:
  - override /environment: mujoco_halfcheetah    
  - override /algorithm: ppo       

# https://huggingface.co/sb3/ppo-HalfCheetah-v3
environment:
  n_envs: 1
  n_total_timesteps: 1000000

hp_config:
  minibatch_size: 64
  clip_eps: 0.1
  ent_coef: 0.000401762
  gae_lambda: 0.92
  gamma: 0.98
  learning_rate: 2.0633e-05
  max_grad_norm: 0.8
  update_epochs: 20
  vf_coef: 0.58096
  n_steps: 512
  normalize_observations: True

nas_config:
  activation: relu
  hidden_size: 256

jax_enable_x64: True
